---

- name: Use standard SSH port
  set_fact:
    ansible_port: 22

- name: Bootstrap Python
  raw: test -e /usr/bin/python || (apt update && apt install -y python-minimal)

- name: Bootstrap Ansible
  raw: apt-get update && apt-get install -y software-properties-common && apt-add-repository -y ppa:ansible/ansible && /usr/bin/apt-get update && /usr/bin/apt-get install -y ansible && /usr/bin/apt-get autoremove -y

- name: Use standard SSH port
  set_fact:
    ansible_port: 22

- import_role:
    name: "nickjj.user"

- name: Disable root login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin yes"
    line: "PermitRootLogin no"

- name: Change ssh port
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#Port 22"
    line: "Port {{ ssh_port }}"

- name: Restart sshd
  service: name=sshd state=restarted
