---

- name: Fix LC_ALL
  lineinfile:
    dest: /etc/default/locale
    state: present
    line: 'LC_ALL="en_US.UTF-8"'

- name: Install base packages
  apt:
    name: "{{ item }}"
  loop:
    - inotify-tools
    - npm
    - mc
    - tmux
    - git
    - lynx
